baseURL = "/"
title = "M. Nouri"

theme = "coder-portfolio"

DefaultContentLanguage = "en"

paginate = 20

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
pygmentsUseClasses = true

disqusShortname = "yourdiscussshortname"

[params]
    author = "Muhannad Nouri"
    description = "Muhannad's Personal Website"
    keywords = "blog,developer,personal"
    info = "Software Developer"
    avatarurl = "https://i.imgur.com/w1ZgXgi.jpg?1"

    hideCredits = false
    hideCopyright = false

    snsShare = true

    thumbnail = "images/tn.png"

    # Custom CSS
    custom_css = []

    # Alignment of Mobile Menu items
    itemscentered = true

    # RTL support
    rtl = false

    langseparator = "|"

[[params.social]]
    name = "GitHub"
    weight = 1
    url = "https://github.com/muhannadnouri/"
[[params.social]]
    name = "LinkedIn"
    weight = 2
    url = "https://ca.linkedin.com/in/muhannadnouri"

[languages]
    [languages.en]
        languagecode = "en"
        languagename = "English" # The language name to be displayed in the selector.
        title = "M. Nouri"

        # You can configure the theme parameter for each language.
        [languages.en.params]
            author = "Muhannad Nouri"
            info = "Software Developer"
            description = "Muhannad's Personal Website"
            keywords = "blog,developer,personal"

        [languages.en.menu] # It is possible to change the menu too.

            [[languages.en.menu.main]]
                name = "About"
                weight = 1.0
                url = "about"

            [[languages.en.menu.main]]
                name = "Blog"
                weight = 2.0
                url = "posts"

            [[languages.en.menu.main]]
                name = "Projects"
                weight = 3
                url = "projects"
            [[languages.en.menu.main]]
                name = "Contact"
                weight = 5
                url = "contact"
